# Generated by Django 4.2.3 on 2023-08-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('businessentityid', models.IntegerField(primary_key=True, serialize=False)),
                ('nationalidnumber', models.CharField(max_length=15)),
                ('loginid', models.CharField(max_length=256, null=True)),
                ('jobtitle', models.CharField(max_length=50)),
                ('birthdate', models.DateField(null=True)),
                ('maritalstatus', models.CharField(max_length=1, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('hiredate', models.DateField()),
                ('salariedflag', models.BooleanField()),
                ('vacationhours', models.SmallIntegerField()),
                ('sickleavehours', models.SmallIntegerField()),
                ('currentflag', models.BooleanField(null=True)),
                ('modifieddate', models.DateTimeField(null=True)),
                ('organizationnode', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
