# Generated by Django 4.2.3 on 2023-08-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleadosapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('groupname', models.CharField(blank=True, max_length=50, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeedepartmenthistory',
            fields=[
                ('employeedepartmenthistoryid', models.AutoField(primary_key=True, serialize=False)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employeedepartmenthistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shiftid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('starttime', models.TimeField(blank=True, null=True)),
                ('endtime', models.TimeField(blank=True, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shift',
                'managed': False,
            },
        ),
    ]
